# Copyright 2025 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
package_json(
    dependencies=[":pnpmrc"],
)

file(name="pnpmrc", source=".pnpmrc")
